class MarketTier {
  final double minPrice;
  final double maxPrice;
  final double projectionBonus;

  const MarketTier({
    required this.minPrice,
    required this.maxPrice,
    this.projectionBonus = 0.0,
  });
}

class WorldCupMarketTiers {
  static const Map<String, MarketTier> byPlayerName = {
    'kylian mbappe': MarketTier(minPrice: 18.0, maxPrice: 20.0, projectionBonus: 1.0),
    'erling haaland': MarketTier(minPrice: 18.0, maxPrice: 20.0, projectionBonus: 1.0),
    'vinicius junior': MarketTier(minPrice: 17.5, maxPrice: 19.0, projectionBonus: 0.9),
    'vinicius jr': MarketTier(minPrice: 17.5, maxPrice: 19.0, projectionBonus: 0.9),
    'jude bellingham': MarketTier(minPrice: 17.0, maxPrice: 18.5, projectionBonus: 0.9),
    'bukayo saka': MarketTier(minPrice: 16.0, maxPrice: 18.0, projectionBonus: 0.8),
    'harry kane': MarketTier(minPrice: 15.5, maxPrice: 17.5, projectionBonus: 0.8),
    'lautaro martinez': MarketTier(minPrice: 15.5, maxPrice: 17.0, projectionBonus: 0.8),
    'julian alvarez': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.8),
    'rodrigo hernandez': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.7),
    'rodri': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.7),
    'pedri': MarketTier(minPrice: 14.0, maxPrice: 16.0, projectionBonus: 0.7),
    'nico williams': MarketTier(minPrice: 13.5, maxPrice: 15.5, projectionBonus: 0.6),
    'federico valverde': MarketTier(minPrice: 14.0, maxPrice: 15.5, projectionBonus: 0.7),
    'bruno fernandes': MarketTier(minPrice: 13.5, maxPrice: 15.0, projectionBonus: 0.7),
    'bernardo silva': MarketTier(minPrice: 13.5, maxPrice: 15.0, projectionBonus: 0.6),
    'rafael leao': MarketTier(minPrice: 13.0, maxPrice: 15.0, projectionBonus: 0.6),
    'khvicha kvaratskhelia': MarketTier(minPrice: 13.0, maxPrice: 15.0, projectionBonus: 0.6),
    'jamal musiala': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.8),
    'florian wirtz': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.8),
    'leroy sane': MarketTier(minPrice: 12.5, maxPrice: 14.5, projectionBonus: 0.5),
    'kevin de bruyne': MarketTier(minPrice: 15.0, maxPrice: 16.5, projectionBonus: 0.7),
    'jeremy doku': MarketTier(minPrice: 12.5, maxPrice: 14.0, projectionBonus: 0.5),
    'romelu lukaku': MarketTier(minPrice: 12.5, maxPrice: 14.5, projectionBonus: 0.5),
    'viktor gyokeres': MarketTier(minPrice: 13.5, maxPrice: 15.5, projectionBonus: 0.6),
    'martin odegaard': MarketTier(minPrice: 13.5, maxPrice: 15.0, projectionBonus: 0.6),
    'alexander isak': MarketTier(minPrice: 13.0, maxPrice: 15.0, projectionBonus: 0.6),
    'mohamed salah': MarketTier(minPrice: 16.0, maxPrice: 18.0, projectionBonus: 0.8),
    'omar marmoush': MarketTier(minPrice: 12.5, maxPrice: 14.5, projectionBonus: 0.5),
    'serhou guirassy': MarketTier(minPrice: 12.0, maxPrice: 14.0, projectionBonus: 0.5),
    'achraf hakimi': MarketTier(minPrice: 12.0, maxPrice: 14.0, projectionBonus: 0.5),
    'hakim ziyech': MarketTier(minPrice: 10.0, maxPrice: 12.5, projectionBonus: 0.3),
    'heung min son': MarketTier(minPrice: 13.5, maxPrice: 15.5, projectionBonus: 0.6),
    'takefusa kubo': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.4),
    'lee kang in': MarketTier(minPrice: 10.0, maxPrice: 12.5, projectionBonus: 0.3),
    'alphonso davies': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.4),
    'jonathan david': MarketTier(minPrice: 12.0, maxPrice: 14.0, projectionBonus: 0.5),
    'christian pulisic': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.4),
    'weston mckennie': MarketTier(minPrice: 9.5, maxPrice: 11.5, projectionBonus: 0.2),
    'tim weah': MarketTier(minPrice: 9.0, maxPrice: 11.0, projectionBonus: 0.2),
    'santiago gimenez': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.5),
    'raul jimenez': MarketTier(minPrice: 9.0, maxPrice: 11.0, projectionBonus: 0.2),
    'edson alvarez': MarketTier(minPrice: 9.5, maxPrice: 11.5, projectionBonus: 0.2),
    'giovanni reyna': MarketTier(minPrice: 9.0, maxPrice: 11.0, projectionBonus: 0.2),
    'robert lewandowski': MarketTier(minPrice: 13.0, maxPrice: 15.0, projectionBonus: 0.5),
    'piotr zielinski': MarketTier(minPrice: 10.0, maxPrice: 12.5, projectionBonus: 0.3),
    'arda guler': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.4),
    'hakan calhanoglu': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.4),
    'dominik szoboszlai': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.4),
    'granit xhaka': MarketTier(minPrice: 9.5, maxPrice: 11.5, projectionBonus: 0.2),
    'manuel akanji': MarketTier(minPrice: 9.5, maxPrice: 11.0, projectionBonus: 0.2),
    'gianluigi donnarumma': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.3),
    'alisson': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.4),
    'emiliano martinez': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.3),
    'thibaut courtois': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.3),
    'virgil van dijk': MarketTier(minPrice: 12.0, maxPrice: 14.0, projectionBonus: 0.4),
    'ruben dias': MarketTier(minPrice: 11.5, maxPrice: 13.5, projectionBonus: 0.3),
    'william saliba': MarketTier(minPrice: 12.0, maxPrice: 14.0, projectionBonus: 0.4),
    'antonio rudiger': MarketTier(minPrice: 11.0, maxPrice: 13.0, projectionBonus: 0.3),
    'joao neves': MarketTier(minPrice: 10.0, maxPrice: 12.5, projectionBonus: 0.3),
  };
}
