// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnp-0BDuWkSAYBm8DVMC9cwJIApw8OG9s',
    appId: '1:1031454409602:web:34caf845bbeee44f2f459b',
    messagingSenderId: '1031454409602',
    projectId: 'paronfantasy',
    authDomain: 'paronfantasy.firebaseapp.com',
    storageBucket: 'paronfantasy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MOuf4tJiWzvsB98TOssxpaAWvNkM0wM',
    appId: '1:1031454409602:android:cbc33c83e1df65c92f459b',
    messagingSenderId: '1031454409602',
    projectId: 'paronfantasy',
    storageBucket: 'paronfantasy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvaQKaqP9JapPeBHem-rZJt-bW5_CVonY',
    appId: '1:1031454409602:ios:d8e587489e18fd662f459b',
    messagingSenderId: '1031454409602',
    projectId: 'paronfantasy',
    storageBucket: 'paronfantasy.firebasestorage.app',
    iosBundleId: 'com.flutter.fantasy11',
  );
}
